{
  '1': 'Identity',
  '2': "Narrator's responses",
  '2.1': 'Terror and Madness Trailer',
  '2.2': 'Intro cinematic',
  '2.3': 'Tutorial lines',
  '2.3.1': 'Entering a building for the first time',
  '2.4': 'Entering the hamlet',
  '2.5': 'Upgrading buildings',
  '2.6': 'Recruiting heroes',
  '2.7': 'Dismissing a hero from the roster',
  '2.8': 'Starting an expedition to kill a boss',
  '2.8.1': 'Ruins',
  '2.8.2': 'Weald',
  '2.8.3': 'Warrens',
  '2.8.4': 'Cove',
  '2.9': 'Entering the Ruins',
  '2.10': 'Entering the Weald',
  '2.11': 'Entering the Warrens',
  '2.12': 'Entering the Coves',
  '2.13': 'Succeeding an expedition',
  '2.13.1': 'Ruins',
  '2.13.2': 'Weald',
  '2.13.3': 'Warrens',
  '2.13.4': 'Cove',
  '2.14': 'Failing an expedition',
  '2.15': 'Encountering a boss',
  '2.16': 'Encountering a Color of Madness boss',
  '2.17': 'Encountering a mini-boss',
  '2.17.1': 'The Collector',
  '2.17.2': 'The Shambler',
  '2.18': 'Encountering a Color of Madness mini-boss',
  '2.18.1': 'The Thing from the Stars',
  '2.19': 'Raising the Light Meter to 100',
  '2.20': 'Light Meter dropping to 0',
  '2.21': 'Obtaining loot',
  '2.22': 'Camping',
  '2.23': 'Getting hit by a trap',
  '2.24': 'Facing obstacles',
  '2.25': 'Failing to satiate the party',
  '2.26': 'Healing',
  '2.26.1': 'Receiving healing through skills and/or food',
  '2.26.2': 'Getting a critical hit when healing',
  '2.26.3': "Healing while at Death's Door",
  '2.27': 'Killing an enemy',
  '2.27.1': 'Killing the first enemy',
  '2.27.2': 'Killing a weak enemy',
  '2.27.3': 'Killing an enemy with a strong attack',
  '2.27.4': 'Killing a large enemy',
  '2.27.5': 'Killing an enemy with blight or bleed',
  '2.28': 'Striking a critical hit',
  '2.29': 'Receiving a critical hit',
  '2.30': 'Receiving a Debuff',
  '2.30.1': 'Being inflicted Horror',
  '2.31': 'Receiving a Buff',
  '2.32': "Having a hero reach Death's Door",
  '2.33': 'Having a hero receive the deathblow',
  '2.34': 'Winning a battle',
  '2.35': 'Filling your inventory',
  '2.36': 'Failing to retreat from a battle',
  '2.37': 'Retreating from a battle',
  '2.38': 'Having a hero reach 50% stress or health',
  '2.39': 'Gaining afflictions',
  '2.40': 'Gaining virtues',
  '2.41': 'Crimson Court DLC cinematic - "Younger Years"',
  '2.42': 'Crimson Court DLC cinematic - "Forbidden Tannin"',
  '2.43': 'Encountering Darkest Dungeon bosses',
  '2.43.1': 'Heart of Darkness'
}